import decodeRanges from '../../decode-ranges.mjs';

export default decodeRanges('wYgAEAAAAEDMAGABgiBHPRglABIAAAABgnCBARCEDAIAAAAABeKCOBDAABCBFhJgghVEBAAJAAJAADBAg2JEBBBACANw8-AXhYNghAA4I-Ugx2JNENDAEACJDiQAAACCABAABAbBlRggAAoLCAQLChbAABDABBABAABAEA4Nk0hD');
