import decodeRanges from '../../decode-ranges.mjs';

export default decodeRanges('gwJwYlJABiCJjFJmbJh1Jh1Jh1Jh1Jh1Jh1Jh1Jh1Jh1JhfJh1JhFJkVJhFJwdFJglJkrJh_JilJFJi1JhVJiFJFJ4InFJqlJglJjFJVJhVJmVJ1ilJwiFJsrJh_Jg7JiPJkVJlVJh1Jl1JhlJhlJmlJhlJr1Jj1JhFJ0y1JjlJ2xzgxwk_JmlJwZVJxKVJ');
