import decodeRanges from '../../decode-ranges.mjs';

export default decodeRanges('wYiDAAAAEDUAgnCACPRglABIAAAABBAAXBfADEDAIAAAAABAcAKCOBDAABCBjFAEBAAJAACNAABg-CAABBFA4QIKAAAABCEJACABAJAiQAACCABAABAAWDl0AoPAfAheCBBBADBEA');
